### ISSUE TITLE
A second HDD created by this role is not useable in guest.

### ISSUE THREAD

**Issue by Tronde** [Tronde/kvm_provision_lab#1]
## Playbook and var file being used

```
---
- name: Provision Debian lab VMs
  hosts: localhost
  debugger: never
  vars_files:
    - roles/kvm_provision_lab/vars/debian11_with_2nd_disk.yml
  tasks:
    - name: Run role kvm_provision_lab
      include_role:
        name: kvm_provision_lab
```

```
---
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_root_pass: "Password"
ssh_key: "ansible_id_rsa.pub"

guests:
  debian-t1:
    vm_ram_mb: 1024
    vm_vcpus: 1
    vm_net: default
    os_type: debian11
    file_type: qcow2
    base_image_name: debian11-template
    vm_template: "debian11-template"
    second_hdd: true
    second_hdd_size: 2G
```

## Expected result

I would have expected that the guest is created with a second disk of a useable size of 2 GiB.

## Actual result

The guest OS shows a usaable size of a few KiB for `/dev/vdb`:

```
# lsblk /dev/vdb
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vdb  254:16   0 192.5K  0 disk
```

The command `qemu-img info /var/lib/libvirt/images/debian-t1-vdb.qcow2` shows it has a usable size of 2 GiB though:

```
$ qemu-img info /var/lib/libvirt/images/debian-t1-vdb.qcow2 
image: /var/lib/libvirt/images/debian-t1-vdb.qcow2
file format: qcow2
virtual size: 2 GiB (2147483648 bytes)
disk size: 196 KiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
```

## Additional information

When an additional disk is created by running `qemu-img create -q -f qcow2 /var/lib/libvirt/images/debian-t1-vdc.qcow2 2G` and attached to the VM it shows the correct size in guest OS:

```
# lsblk /dev/vd{b,c}
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vdb  254:16   0 192.5K  0 disk 
vdc  254:32   0     2G  0 disk
```

And it gets weird:

```
$ qemu-img info /var/lib/libvirt/images/debian-t1-vdc.qcow2
image: /var/lib/libvirt/images/debian-t1-vdc.qcow2
file format: qcow2
virtual size: 2 GiB (2147483648 bytes)
disk size: 196 KiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false

$ qemu-img compare /var/lib/libvirt/images/debian-t1-vdb.qcow2 /var/lib/libvirt/images/debian-t1-vdc.qcow2
Images are identical.
``

So far I have absolutely no clue and now idea what causes this. Help would be much appreciated.
